// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6QumENyvTgbvbglqDb3d9EywKwKBQBeI',
    appId: '1:254143117772:web:97067adddfd9729ba18569',
    messagingSenderId: '254143117772',
    projectId: 'ai-chat-3f7eb',
    authDomain: 'ai-chat-3f7eb.firebaseapp.com',
    storageBucket: 'ai-chat-3f7eb.firebasestorage.app',
    measurementId: 'G-Z96JRLPYJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZZnqLDuCK5OjWinZkPvSRKLQNosNDYcQ',
    appId: '1:254143117772:android:3ac4b75512253aa0a18569',
    messagingSenderId: '254143117772',
    projectId: 'ai-chat-3f7eb',
    storageBucket: 'ai-chat-3f7eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB72vZ0tLTk4muJP-JNc3Wgv8HvK83a-MU',
    appId: '1:254143117772:ios:09cb4231b9ad2817a18569',
    messagingSenderId: '254143117772',
    projectId: 'ai-chat-3f7eb',
    storageBucket: 'ai-chat-3f7eb.firebasestorage.app',
    iosBundleId: 'com.example.aiChatbot',
  );
}
